#manifest:
#  remotes:
#    - name: zmkfirmware
#      url-base: https://github.com/zmkfirmware
#  projects:
#    - name: zmk
#      remote: zmkfirmware
#      revision: main
#      import: app/west.yml
#  self:
#    path: config

manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/drorchen
  projects:
    - name: zmk
      remote: zmk
      revision: trackball-support
      import: app/west.yml
  self:
    path: config