#manifest:
#  remotes:
#    - name: zmkfirmware
#      url-base: https://github.com/zmkfirmware
#  projects:
#    - name: zmk
#      remote: zmkfirmware
#      revision: main
#      import: app/west.yml
#  self:
#    path: config

manifest:
  remotes:
    - name: bullwinkle3000
      url-base: https://github.com/bullwinkle3000
  projects:
    - name: zmk
      remote: bullwinkle3000
      revision: feat/pointers-pmw3360
      import: app/west.yml
  self:
    path: config